// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
   Bit,
   Char,
   CodecTypes as PgTypes,
   Interval,
   JsonValue,
   Numeric,
   Time,
   TimeString,
   Timestamp,
   TimestampString,
   Timestamptz,
   TimestamptzString,
   Timetz,
   VarBit,
   Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
   ContractWithTypeMaps,
   RelationKeys,
   TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
   Contract as ContractType,
   ExecutionHashBase,
   NamespaceId,
   ProfileHashBase,
   StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
   StorageHashBase<'fdfee8a763c0359398d8f6ba36c4b27d120781361425e275b3f2bc693546ea55'>;
export type ExecutionHash =
   ExecutionHashBase<'deca7024a189a6108da9e662bc0fe69968c8d4f1c71293e8099771369c7d7065'>;
export type ProfileHash =
   ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
   readonly avg: {
      readonly byCodec: {
         readonly 'pg/float@1': {
            readonly output: 'pg/float8@1';
            readonly nullable: true;
         };
         readonly 'pg/float4@1': {
            readonly output: 'pg/float8@1';
            readonly nullable: true;
         };
         readonly 'pg/float8@1': {
            readonly output: 'pg/float8@1';
            readonly nullable: true;
         };
         readonly 'pg/int@1': {
            readonly output: 'pg/float8@1';
            readonly nullable: true;
         };
         readonly 'pg/int2@1': {
            readonly output: 'pg/float8@1';
            readonly nullable: true;
         };
         readonly 'pg/int4@1': {
            readonly output: 'pg/float8@1';
            readonly nullable: true;
         };
         readonly 'pg/int8@1': {
            readonly output: 'pg/float8@1';
            readonly nullable: true;
         };
         readonly 'pg/int8number@1': {
            readonly output: 'pg/float8@1';
            readonly nullable: true;
         };
         readonly 'pg/interval@1': {
            readonly output: 'pg/interval@1';
            readonly nullable: true;
         };
         readonly 'pg/numeric@1': {
            readonly output: 'pg/numeric@1';
            readonly nullable: true;
         };
         readonly 'pg/time-string@1': {
            readonly output: 'pg/interval@1';
            readonly nullable: true;
         };
         readonly 'pg/time-temporal@1': {
            readonly output: 'pg/interval@1';
            readonly nullable: true;
         };
         readonly 'pg/unboundedint@1': {
            readonly output: 'pg/float8@1';
            readonly nullable: true;
         };
         readonly 'sql/float@1': {
            readonly output: 'pg/float8@1';
            readonly nullable: true;
         };
         readonly 'sql/int@1': {
            readonly output: 'pg/float8@1';
            readonly nullable: true;
         };
      };
   };
   readonly avgDecimal: {
      readonly byCodec: {
         readonly 'pg/int@1': {
            readonly output: 'pg/numeric@1';
            readonly nullable: true;
         };
         readonly 'pg/int2@1': {
            readonly output: 'pg/numeric@1';
            readonly nullable: true;
         };
         readonly 'pg/int4@1': {
            readonly output: 'pg/numeric@1';
            readonly nullable: true;
         };
         readonly 'pg/int8@1': {
            readonly output: 'pg/numeric@1';
            readonly nullable: true;
         };
         readonly 'pg/int8number@1': {
            readonly output: 'pg/numeric@1';
            readonly nullable: true;
         };
         readonly 'pg/numeric@1': {
            readonly output: 'pg/numeric@1';
            readonly nullable: true;
         };
         readonly 'pg/unboundedint@1': {
            readonly output: 'pg/numeric@1';
            readonly nullable: true;
         };
         readonly 'sql/int@1': {
            readonly output: 'pg/numeric@1';
            readonly nullable: true;
         };
      };
   };
   readonly count: {
      readonly byCodec: {};
      readonly withoutInput: {
         readonly output: 'pg/int8number@1';
         readonly nullable: false;
      };
      readonly anyInput: {
         readonly output: 'pg/int8number@1';
         readonly nullable: false;
      };
   };
   readonly countBigInt: {
      readonly byCodec: {};
      readonly withoutInput: {
         readonly output: 'pg/int8@1';
         readonly nullable: false;
      };
      readonly anyInput: {
         readonly output: 'pg/int8@1';
         readonly nullable: false;
      };
   };
   readonly max: {
      readonly byCodec: {
         readonly 'pg/char@1': {
            readonly output: 'pg/char@1';
            readonly nullable: true;
         };
         readonly 'pg/date-string@1': {
            readonly output: 'pg/date-string@1';
            readonly nullable: true;
         };
         readonly 'pg/date-temporal@1': {
            readonly output: 'pg/date-temporal@1';
            readonly nullable: true;
         };
         readonly 'pg/enum@1': {
            readonly output: 'pg/enum@1';
            readonly nullable: true;
         };
         readonly 'pg/float@1': {
            readonly output: 'pg/float@1';
            readonly nullable: true;
         };
         readonly 'pg/float4@1': {
            readonly output: 'pg/float4@1';
            readonly nullable: true;
         };
         readonly 'pg/float8@1': {
            readonly output: 'pg/float8@1';
            readonly nullable: true;
         };
         readonly 'pg/inet@1': {
            readonly output: 'pg/inet@1';
            readonly nullable: true;
         };
         readonly 'pg/int@1': {
            readonly output: 'pg/int@1';
            readonly nullable: true;
         };
         readonly 'pg/int2@1': {
            readonly output: 'pg/int2@1';
            readonly nullable: true;
         };
         readonly 'pg/int4@1': {
            readonly output: 'pg/int4@1';
            readonly nullable: true;
         };
         readonly 'pg/int8@1': {
            readonly output: 'pg/int8@1';
            readonly nullable: true;
         };
         readonly 'pg/int8number@1': {
            readonly output: 'pg/int8number@1';
            readonly nullable: true;
         };
         readonly 'pg/interval@1': {
            readonly output: 'pg/interval@1';
            readonly nullable: true;
         };
         readonly 'pg/numeric@1': {
            readonly output: 'pg/numeric@1';
            readonly nullable: true;
         };
         readonly 'pg/text-array@1': {
            readonly output: 'pg/text-array@1';
            readonly nullable: true;
         };
         readonly 'pg/text@1': {
            readonly output: 'pg/text@1';
            readonly nullable: true;
         };
         readonly 'pg/time-string@1': {
            readonly output: 'pg/time-string@1';
            readonly nullable: true;
         };
         readonly 'pg/time-temporal@1': {
            readonly output: 'pg/time-temporal@1';
            readonly nullable: true;
         };
         readonly 'pg/timestamp-string@1': {
            readonly output: 'pg/timestamp-string@1';
            readonly nullable: true;
         };
         readonly 'pg/timestamp-temporal@1': {
            readonly output: 'pg/timestamp-temporal@1';
            readonly nullable: true;
         };
         readonly 'pg/timestamptz-string@1': {
            readonly output: 'pg/timestamptz-string@1';
            readonly nullable: true;
         };
         readonly 'pg/timestamptz-temporal@1': {
            readonly output: 'pg/timestamptz-temporal@1';
            readonly nullable: true;
         };
         readonly 'pg/timetz@1': {
            readonly output: 'pg/timetz@1';
            readonly nullable: true;
         };
         readonly 'pg/unboundedint@1': {
            readonly output: 'pg/unboundedint@1';
            readonly nullable: true;
         };
         readonly 'pg/varchar@1': {
            readonly output: 'pg/text@1';
            readonly nullable: true;
         };
         readonly 'sql/char@1': {
            readonly output: 'sql/char@1';
            readonly nullable: true;
         };
         readonly 'sql/float@1': {
            readonly output: 'sql/float@1';
            readonly nullable: true;
         };
         readonly 'sql/int@1': {
            readonly output: 'sql/int@1';
            readonly nullable: true;
         };
         readonly 'sql/text@1': {
            readonly output: 'sql/text@1';
            readonly nullable: true;
         };
         readonly 'sql/varchar@1': {
            readonly output: 'pg/text@1';
            readonly nullable: true;
         };
      };
   };
   readonly min: {
      readonly byCodec: {
         readonly 'pg/char@1': {
            readonly output: 'pg/char@1';
            readonly nullable: true;
         };
         readonly 'pg/date-string@1': {
            readonly output: 'pg/date-string@1';
            readonly nullable: true;
         };
         readonly 'pg/date-temporal@1': {
            readonly output: 'pg/date-temporal@1';
            readonly nullable: true;
         };
         readonly 'pg/enum@1': {
            readonly output: 'pg/enum@1';
            readonly nullable: true;
         };
         readonly 'pg/float@1': {
            readonly output: 'pg/float@1';
            readonly nullable: true;
         };
         readonly 'pg/float4@1': {
            readonly output: 'pg/float4@1';
            readonly nullable: true;
         };
         readonly 'pg/float8@1': {
            readonly output: 'pg/float8@1';
            readonly nullable: true;
         };
         readonly 'pg/inet@1': {
            readonly output: 'pg/inet@1';
            readonly nullable: true;
         };
         readonly 'pg/int@1': {
            readonly output: 'pg/int@1';
            readonly nullable: true;
         };
         readonly 'pg/int2@1': {
            readonly output: 'pg/int2@1';
            readonly nullable: true;
         };
         readonly 'pg/int4@1': {
            readonly output: 'pg/int4@1';
            readonly nullable: true;
         };
         readonly 'pg/int8@1': {
            readonly output: 'pg/int8@1';
            readonly nullable: true;
         };
         readonly 'pg/int8number@1': {
            readonly output: 'pg/int8number@1';
            readonly nullable: true;
         };
         readonly 'pg/interval@1': {
            readonly output: 'pg/interval@1';
            readonly nullable: true;
         };
         readonly 'pg/numeric@1': {
            readonly output: 'pg/numeric@1';
            readonly nullable: true;
         };
         readonly 'pg/text-array@1': {
            readonly output: 'pg/text-array@1';
            readonly nullable: true;
         };
         readonly 'pg/text@1': {
            readonly output: 'pg/text@1';
            readonly nullable: true;
         };
         readonly 'pg/time-string@1': {
            readonly output: 'pg/time-string@1';
            readonly nullable: true;
         };
         readonly 'pg/time-temporal@1': {
            readonly output: 'pg/time-temporal@1';
            readonly nullable: true;
         };
         readonly 'pg/timestamp-string@1': {
            readonly output: 'pg/timestamp-string@1';
            readonly nullable: true;
         };
         readonly 'pg/timestamp-temporal@1': {
            readonly output: 'pg/timestamp-temporal@1';
            readonly nullable: true;
         };
         readonly 'pg/timestamptz-string@1': {
            readonly output: 'pg/timestamptz-string@1';
            readonly nullable: true;
         };
         readonly 'pg/timestamptz-temporal@1': {
            readonly output: 'pg/timestamptz-temporal@1';
            readonly nullable: true;
         };
         readonly 'pg/timetz@1': {
            readonly output: 'pg/timetz@1';
            readonly nullable: true;
         };
         readonly 'pg/unboundedint@1': {
            readonly output: 'pg/unboundedint@1';
            readonly nullable: true;
         };
         readonly 'pg/varchar@1': {
            readonly output: 'pg/text@1';
            readonly nullable: true;
         };
         readonly 'sql/char@1': {
            readonly output: 'sql/char@1';
            readonly nullable: true;
         };
         readonly 'sql/float@1': {
            readonly output: 'sql/float@1';
            readonly nullable: true;
         };
         readonly 'sql/int@1': {
            readonly output: 'sql/int@1';
            readonly nullable: true;
         };
         readonly 'sql/text@1': {
            readonly output: 'sql/text@1';
            readonly nullable: true;
         };
         readonly 'sql/varchar@1': {
            readonly output: 'pg/text@1';
            readonly nullable: true;
         };
      };
   };
   readonly sum: {
      readonly byCodec: {
         readonly 'pg/float@1': {
            readonly output: 'pg/float8@1';
            readonly nullable: true;
         };
         readonly 'pg/float4@1': {
            readonly output: 'pg/float4@1';
            readonly nullable: true;
         };
         readonly 'pg/float8@1': {
            readonly output: 'pg/float8@1';
            readonly nullable: true;
         };
         readonly 'pg/int@1': {
            readonly output: 'pg/int8number@1';
            readonly nullable: true;
         };
         readonly 'pg/int2@1': {
            readonly output: 'pg/int8number@1';
            readonly nullable: true;
         };
         readonly 'pg/int4@1': {
            readonly output: 'pg/int8number@1';
            readonly nullable: true;
         };
         readonly 'pg/int8@1': {
            readonly output: 'pg/int8number@1';
            readonly nullable: true;
         };
         readonly 'pg/int8number@1': {
            readonly output: 'pg/int8number@1';
            readonly nullable: true;
         };
         readonly 'pg/interval@1': {
            readonly output: 'pg/interval@1';
            readonly nullable: true;
         };
         readonly 'pg/numeric@1': {
            readonly output: 'pg/numeric@1';
            readonly nullable: true;
         };
         readonly 'pg/time-string@1': {
            readonly output: 'pg/interval@1';
            readonly nullable: true;
         };
         readonly 'pg/time-temporal@1': {
            readonly output: 'pg/interval@1';
            readonly nullable: true;
         };
         readonly 'pg/unboundedint@1': {
            readonly output: 'pg/unboundedint@1';
            readonly nullable: true;
         };
         readonly 'sql/float@1': {
            readonly output: 'pg/float8@1';
            readonly nullable: true;
         };
         readonly 'sql/int@1': {
            readonly output: 'pg/int8number@1';
            readonly nullable: true;
         };
      };
   };
   readonly sumBigInt: {
      readonly byCodec: {
         readonly 'pg/int@1': {
            readonly output: 'pg/int8@1';
            readonly nullable: true;
         };
         readonly 'pg/int2@1': {
            readonly output: 'pg/int8@1';
            readonly nullable: true;
         };
         readonly 'pg/int4@1': {
            readonly output: 'pg/int8@1';
            readonly nullable: true;
         };
         readonly 'pg/int8@1': {
            readonly output: 'pg/unboundedint@1';
            readonly nullable: true;
         };
         readonly 'pg/int8number@1': {
            readonly output: 'pg/unboundedint@1';
            readonly nullable: true;
         };
         readonly 'pg/unboundedint@1': {
            readonly output: 'pg/unboundedint@1';
            readonly nullable: true;
         };
         readonly 'sql/int@1': {
            readonly output: 'pg/int8@1';
            readonly nullable: true;
         };
      };
   };
};
type DefaultLiteralValue<
   CodecId extends string,
   Encoded,
> = CodecId extends keyof CodecTypes
   ? Encoded extends CodecTypes[CodecId]['json']
      ? Encoded
      : CodecTypes[CodecId]['json']
   : Encoded;

export type FieldOutputTypes = {
   readonly public: {
      readonly Comment: {
         readonly id: CodecTypes['pg/text@1']['output'];
         readonly comment: CodecTypes['pg/text@1']['output'];
         readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
         readonly userId: CodecTypes['pg/text@1']['output'];
         readonly postId: CodecTypes['pg/text@1']['output'];
      };
      readonly Follow: {
         readonly followerId: CodecTypes['pg/text@1']['output'];
         readonly followingId: CodecTypes['pg/text@1']['output'];
         readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      };
      readonly Like: {
         readonly userId: CodecTypes['pg/text@1']['output'];
         readonly postId: CodecTypes['pg/text@1']['output'];
      };
      readonly Post: {
         readonly id: CodecTypes['pg/text@1']['output'];
         readonly title: CodecTypes['pg/text@1']['output'];
         readonly content: CodecTypes['pg/text@1']['output'];
         readonly slug: CodecTypes['pg/text@1']['output'];
         readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
         readonly published_at:
            CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
         readonly authorId: CodecTypes['pg/text@1']['output'];
      };
      readonly Post_Tag: {
         readonly postId: CodecTypes['pg/text@1']['output'];
         readonly tagId: CodecTypes['pg/text@1']['output'];
      };
      readonly Tag: {
         readonly id: CodecTypes['pg/text@1']['output'];
         readonly name: CodecTypes['pg/text@1']['output'];
      };
      readonly User: {
         readonly id: CodecTypes['pg/text@1']['output'];
         readonly name: CodecTypes['pg/text@1']['output'];
         readonly email: CodecTypes['pg/text@1']['output'];
         readonly bio: CodecTypes['pg/text@1']['output'] | null;
         readonly password: CodecTypes['pg/text@1']['output'];
      };
   };
};
export type FieldInputTypes = {
   readonly public: {
      readonly Comment: {
         readonly id: CodecTypes['pg/text@1']['input'];
         readonly comment: CodecTypes['pg/text@1']['input'];
         readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
         readonly userId: CodecTypes['pg/text@1']['input'];
         readonly postId: CodecTypes['pg/text@1']['input'];
      };
      readonly Follow: {
         readonly followerId: CodecTypes['pg/text@1']['input'];
         readonly followingId: CodecTypes['pg/text@1']['input'];
         readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      };
      readonly Like: {
         readonly userId: CodecTypes['pg/text@1']['input'];
         readonly postId: CodecTypes['pg/text@1']['input'];
      };
      readonly Post: {
         readonly id: CodecTypes['pg/text@1']['input'];
         readonly title: CodecTypes['pg/text@1']['input'];
         readonly content: CodecTypes['pg/text@1']['input'];
         readonly slug: CodecTypes['pg/text@1']['input'];
         readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
         readonly published_at:
            CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
         readonly authorId: CodecTypes['pg/text@1']['input'];
      };
      readonly Post_Tag: {
         readonly postId: CodecTypes['pg/text@1']['input'];
         readonly tagId: CodecTypes['pg/text@1']['input'];
      };
      readonly Tag: {
         readonly id: CodecTypes['pg/text@1']['input'];
         readonly name: CodecTypes['pg/text@1']['input'];
      };
      readonly User: {
         readonly id: CodecTypes['pg/text@1']['input'];
         readonly name: CodecTypes['pg/text@1']['input'];
         readonly email: CodecTypes['pg/text@1']['input'];
         readonly bio: CodecTypes['pg/text@1']['input'] | null;
         readonly password: CodecTypes['pg/text@1']['input'];
      };
   };
};
export type StorageColumnTypes = {
   readonly public: {
      readonly comment: {
         readonly comment: CodecTypes['pg/text@1']['output'];
         readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
         readonly id: CodecTypes['pg/text@1']['output'];
         readonly postId: CodecTypes['pg/text@1']['output'];
         readonly userId: CodecTypes['pg/text@1']['output'];
      };
      readonly follow: {
         readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
         readonly followerId: CodecTypes['pg/text@1']['output'];
         readonly followingId: CodecTypes['pg/text@1']['output'];
      };
      readonly like: {
         readonly postId: CodecTypes['pg/text@1']['output'];
         readonly userId: CodecTypes['pg/text@1']['output'];
      };
      readonly post: {
         readonly authorId: CodecTypes['pg/text@1']['output'];
         readonly content: CodecTypes['pg/text@1']['output'];
         readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
         readonly id: CodecTypes['pg/text@1']['output'];
         readonly published_at:
            CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
         readonly slug: CodecTypes['pg/text@1']['output'];
         readonly title: CodecTypes['pg/text@1']['output'];
      };
      readonly post_Tag: {
         readonly postId: CodecTypes['pg/text@1']['output'];
         readonly tagId: CodecTypes['pg/text@1']['output'];
      };
      readonly tag: {
         readonly id: CodecTypes['pg/text@1']['output'];
         readonly name: CodecTypes['pg/text@1']['output'];
      };
      readonly user: {
         readonly bio: CodecTypes['pg/text@1']['output'] | null;
         readonly email: CodecTypes['pg/text@1']['output'];
         readonly id: CodecTypes['pg/text@1']['output'];
         readonly name: CodecTypes['pg/text@1']['output'];
         readonly password: CodecTypes['pg/text@1']['output'];
      };
   };
};
export type StorageColumnInputTypes = {
   readonly public: {
      readonly comment: {
         readonly comment: CodecTypes['pg/text@1']['input'];
         readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
         readonly id: CodecTypes['pg/text@1']['input'];
         readonly postId: CodecTypes['pg/text@1']['input'];
         readonly userId: CodecTypes['pg/text@1']['input'];
      };
      readonly follow: {
         readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
         readonly followerId: CodecTypes['pg/text@1']['input'];
         readonly followingId: CodecTypes['pg/text@1']['input'];
      };
      readonly like: {
         readonly postId: CodecTypes['pg/text@1']['input'];
         readonly userId: CodecTypes['pg/text@1']['input'];
      };
      readonly post: {
         readonly authorId: CodecTypes['pg/text@1']['input'];
         readonly content: CodecTypes['pg/text@1']['input'];
         readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
         readonly id: CodecTypes['pg/text@1']['input'];
         readonly published_at:
            CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
         readonly slug: CodecTypes['pg/text@1']['input'];
         readonly title: CodecTypes['pg/text@1']['input'];
      };
      readonly post_Tag: {
         readonly postId: CodecTypes['pg/text@1']['input'];
         readonly tagId: CodecTypes['pg/text@1']['input'];
      };
      readonly tag: {
         readonly id: CodecTypes['pg/text@1']['input'];
         readonly name: CodecTypes['pg/text@1']['input'];
      };
      readonly user: {
         readonly bio: CodecTypes['pg/text@1']['input'] | null;
         readonly email: CodecTypes['pg/text@1']['input'];
         readonly id: CodecTypes['pg/text@1']['input'];
         readonly name: CodecTypes['pg/text@1']['input'];
         readonly password: CodecTypes['pg/text@1']['input'];
      };
   };
};

export namespace Models {
   export type public_User = {
      id: CodecTypes['pg/text@1']['output'];
      name: CodecTypes['pg/text@1']['output'];
      email: CodecTypes['pg/text@1']['output'];
      bio: CodecTypes['pg/text@1']['output'] | null;
      password: CodecTypes['pg/text@1']['output'];
      comments: public_Comment[];
      followers: public_Follow[];
      following: public_Follow[];
      likes: public_Like[];
      posts: public_Post[];
      readonly [RelationKeys]?:
         'comments' | 'followers' | 'following' | 'likes' | 'posts';
   };
   export type public_Post = {
      id: CodecTypes['pg/text@1']['output'];
      title: CodecTypes['pg/text@1']['output'];
      content: CodecTypes['pg/text@1']['output'];
      slug: CodecTypes['pg/text@1']['output'];
      created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      published_at: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      authorId: CodecTypes['pg/text@1']['output'];
      author: public_User;
      comments: public_Comment[];
      likes: public_Like[];
      tags: public_Post_Tag[];
      readonly [RelationKeys]?: 'author' | 'comments' | 'likes' | 'tags';
   };
   export type public_Tag = {
      id: CodecTypes['pg/text@1']['output'];
      name: CodecTypes['pg/text@1']['output'];
      postTags: public_Post_Tag[];
      readonly [RelationKeys]?: 'postTags';
   };
   export type public_Post_Tag = {
      postId: CodecTypes['pg/text@1']['output'];
      tagId: CodecTypes['pg/text@1']['output'];
      post: public_Post;
      tag: public_Tag;
      readonly [RelationKeys]?: 'post' | 'tag';
   };
   export type public_Follow = {
      followerId: CodecTypes['pg/text@1']['output'];
      followingId: CodecTypes['pg/text@1']['output'];
      createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      follower: public_User;
      following: public_User;
      readonly [RelationKeys]?: 'follower' | 'following';
   };
   export type public_Like = {
      userId: CodecTypes['pg/text@1']['output'];
      postId: CodecTypes['pg/text@1']['output'];
      post: public_Post;
      user: public_User;
      readonly [RelationKeys]?: 'post' | 'user';
   };
   export type public_Comment = {
      id: CodecTypes['pg/text@1']['output'];
      comment: CodecTypes['pg/text@1']['output'];
      created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      userId: CodecTypes['pg/text@1']['output'];
      postId: CodecTypes['pg/text@1']['output'];
      post: public_Post;
      user: public_User;
      readonly [RelationKeys]?: 'post' | 'user';
   };
}

export declare const models: {
   public: {
      User: Models.public_User;
      Post: Models.public_Post;
      Tag: Models.public_Tag;
      Post_Tag: Models.public_Post_Tag;
      Follow: Models.public_Follow;
      Like: Models.public_Like;
      Comment: Models.public_Comment;
   };
};

export type TypeMaps = TypeMapsType<
   CodecTypes,
   QueryOperationTypes,
   FieldOutputTypes,
   FieldInputTypes,
   StorageColumnTypes,
   StorageColumnInputTypes,
   AggregateTypes
>;

type ContractBase = Omit<
   ContractType<{
      readonly namespaces: {
         readonly public: {
            readonly id: 'public';
            readonly kind: 'postgres-schema';
            readonly entries: {
               readonly table: {
                  readonly comment: {
                     columns: {
                        readonly id: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                        readonly comment: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                        readonly created_at: {
                           readonly nativeType: 'timestamptz';
                           readonly codecId: 'pg/timestamptz-temporal@1';
                           readonly nullable: false;
                           readonly default: {
                              readonly kind: 'function';
                              readonly expression: 'now()';
                           };
                        };
                        readonly userId: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                        readonly postId: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                     };
                     primaryKey: { readonly columns: readonly ['id'] };
                     uniques: readonly [];
                     indexes: readonly [
                        {
                           readonly name: 'comment_userId_idx_a489d58a';
                           readonly prefix: 'comment_userId_idx';
                           readonly columns: readonly ['userId'];
                           readonly unique: false;
                        },
                        {
                           readonly name: 'comment_postId_idx_a7a72715';
                           readonly prefix: 'comment_postId_idx';
                           readonly columns: readonly ['postId'];
                           readonly unique: false;
                        },
                     ];
                     foreignKeys: readonly [
                        {
                           readonly source: {
                              readonly namespaceId: 'public' & NamespaceId;
                              readonly tableName: 'comment';
                              readonly columns: readonly ['userId'];
                           };
                           readonly target: {
                              readonly namespaceId: 'public' & NamespaceId;
                              readonly tableName: 'user';
                              readonly columns: readonly ['id'];
                           };
                        },
                        {
                           readonly source: {
                              readonly namespaceId: 'public' & NamespaceId;
                              readonly tableName: 'comment';
                              readonly columns: readonly ['postId'];
                           };
                           readonly target: {
                              readonly namespaceId: 'public' & NamespaceId;
                              readonly tableName: 'post';
                              readonly columns: readonly ['id'];
                           };
                        },
                     ];
                  };
                  readonly follow: {
                     columns: {
                        readonly followerId: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                        readonly followingId: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                        readonly createdAt: {
                           readonly nativeType: 'timestamptz';
                           readonly codecId: 'pg/timestamptz-temporal@1';
                           readonly nullable: false;
                           readonly default: {
                              readonly kind: 'function';
                              readonly expression: 'now()';
                           };
                        };
                     };
                     primaryKey: {
                        readonly columns: readonly [
                           'followerId',
                           'followingId',
                        ];
                     };
                     uniques: readonly [];
                     indexes: readonly [
                        {
                           readonly name: 'follow_followerId_idx_2aa6c62d';
                           readonly prefix: 'follow_followerId_idx';
                           readonly columns: readonly ['followerId'];
                           readonly unique: false;
                        },
                        {
                           readonly name: 'follow_followingId_idx_1cf16645';
                           readonly prefix: 'follow_followingId_idx';
                           readonly columns: readonly ['followingId'];
                           readonly unique: false;
                        },
                     ];
                     foreignKeys: readonly [
                        {
                           readonly source: {
                              readonly namespaceId: 'public' & NamespaceId;
                              readonly tableName: 'follow';
                              readonly columns: readonly ['followerId'];
                           };
                           readonly target: {
                              readonly namespaceId: 'public' & NamespaceId;
                              readonly tableName: 'user';
                              readonly columns: readonly ['id'];
                           };
                        },
                        {
                           readonly source: {
                              readonly namespaceId: 'public' & NamespaceId;
                              readonly tableName: 'follow';
                              readonly columns: readonly ['followingId'];
                           };
                           readonly target: {
                              readonly namespaceId: 'public' & NamespaceId;
                              readonly tableName: 'user';
                              readonly columns: readonly ['id'];
                           };
                        },
                     ];
                  };
                  readonly like: {
                     columns: {
                        readonly userId: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                        readonly postId: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                     };
                     primaryKey: {
                        readonly columns: readonly ['userId', 'postId'];
                     };
                     uniques: readonly [];
                     indexes: readonly [
                        {
                           readonly name: 'like_userId_idx_a489d58a';
                           readonly prefix: 'like_userId_idx';
                           readonly columns: readonly ['userId'];
                           readonly unique: false;
                        },
                        {
                           readonly name: 'like_postId_idx_a7a72715';
                           readonly prefix: 'like_postId_idx';
                           readonly columns: readonly ['postId'];
                           readonly unique: false;
                        },
                     ];
                     foreignKeys: readonly [
                        {
                           readonly source: {
                              readonly namespaceId: 'public' & NamespaceId;
                              readonly tableName: 'like';
                              readonly columns: readonly ['userId'];
                           };
                           readonly target: {
                              readonly namespaceId: 'public' & NamespaceId;
                              readonly tableName: 'user';
                              readonly columns: readonly ['id'];
                           };
                        },
                        {
                           readonly source: {
                              readonly namespaceId: 'public' & NamespaceId;
                              readonly tableName: 'like';
                              readonly columns: readonly ['postId'];
                           };
                           readonly target: {
                              readonly namespaceId: 'public' & NamespaceId;
                              readonly tableName: 'post';
                              readonly columns: readonly ['id'];
                           };
                        },
                     ];
                  };
                  readonly post: {
                     columns: {
                        readonly id: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                        readonly title: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                        readonly content: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                        readonly slug: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                        readonly created_at: {
                           readonly nativeType: 'timestamptz';
                           readonly codecId: 'pg/timestamptz-temporal@1';
                           readonly nullable: false;
                           readonly default: {
                              readonly kind: 'function';
                              readonly expression: 'now()';
                           };
                        };
                        readonly published_at: {
                           readonly nativeType: 'timestamptz';
                           readonly codecId: 'pg/timestamptz-temporal@1';
                           readonly nullable: true;
                        };
                        readonly authorId: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                     };
                     primaryKey: { readonly columns: readonly ['id'] };
                     uniques: readonly [
                        { readonly columns: readonly ['slug'] },
                     ];
                     indexes: readonly [
                        {
                           readonly name: 'post_authorId_idx_e47547ed';
                           readonly prefix: 'post_authorId_idx';
                           readonly columns: readonly ['authorId'];
                           readonly unique: false;
                        },
                     ];
                     foreignKeys: readonly [
                        {
                           readonly source: {
                              readonly namespaceId: 'public' & NamespaceId;
                              readonly tableName: 'post';
                              readonly columns: readonly ['authorId'];
                           };
                           readonly target: {
                              readonly namespaceId: 'public' & NamespaceId;
                              readonly tableName: 'user';
                              readonly columns: readonly ['id'];
                           };
                        },
                     ];
                  };
                  readonly post_Tag: {
                     columns: {
                        readonly postId: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                        readonly tagId: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                     };
                     primaryKey: {
                        readonly columns: readonly ['postId', 'tagId'];
                     };
                     uniques: readonly [];
                     indexes: readonly [
                        {
                           readonly name: 'post_Tag_postId_idx_a7a72715';
                           readonly prefix: 'post_Tag_postId_idx';
                           readonly columns: readonly ['postId'];
                           readonly unique: false;
                        },
                        {
                           readonly name: 'post_Tag_tagId_idx_86854244';
                           readonly prefix: 'post_Tag_tagId_idx';
                           readonly columns: readonly ['tagId'];
                           readonly unique: false;
                        },
                     ];
                     foreignKeys: readonly [
                        {
                           readonly source: {
                              readonly namespaceId: 'public' & NamespaceId;
                              readonly tableName: 'post_Tag';
                              readonly columns: readonly ['postId'];
                           };
                           readonly target: {
                              readonly namespaceId: 'public' & NamespaceId;
                              readonly tableName: 'post';
                              readonly columns: readonly ['id'];
                           };
                        },
                        {
                           readonly source: {
                              readonly namespaceId: 'public' & NamespaceId;
                              readonly tableName: 'post_Tag';
                              readonly columns: readonly ['tagId'];
                           };
                           readonly target: {
                              readonly namespaceId: 'public' & NamespaceId;
                              readonly tableName: 'tag';
                              readonly columns: readonly ['id'];
                           };
                        },
                     ];
                  };
                  readonly tag: {
                     columns: {
                        readonly id: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                        readonly name: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                     };
                     primaryKey: { readonly columns: readonly ['id'] };
                     uniques: readonly [
                        { readonly columns: readonly ['name'] },
                     ];
                     indexes: readonly [];
                     foreignKeys: readonly [];
                  };
                  readonly user: {
                     columns: {
                        readonly id: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                        readonly name: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                        readonly email: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                        readonly bio: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: true;
                        };
                        readonly password: {
                           readonly nativeType: 'text';
                           readonly codecId: 'pg/text@1';
                           readonly nullable: false;
                        };
                     };
                     primaryKey: { readonly columns: readonly ['id'] };
                     uniques: readonly [
                        { readonly columns: readonly ['email'] },
                     ];
                     indexes: readonly [];
                     foreignKeys: readonly [];
                  };
               };
            };
         };
      };
      readonly storageHash: StorageHash;
   }>,
   'roots' | 'domain'
> & {
   readonly target: 'postgres';
   readonly targetFamily: 'sql';
   readonly roots: {
      readonly user: {
         readonly namespace: 'public' & NamespaceId;
         readonly model: 'User';
      };
      readonly post: {
         readonly namespace: 'public' & NamespaceId;
         readonly model: 'Post';
      };
      readonly tag: {
         readonly namespace: 'public' & NamespaceId;
         readonly model: 'Tag';
      };
      readonly post_Tag: {
         readonly namespace: 'public' & NamespaceId;
         readonly model: 'Post_Tag';
      };
      readonly follow: {
         readonly namespace: 'public' & NamespaceId;
         readonly model: 'Follow';
      };
      readonly like: {
         readonly namespace: 'public' & NamespaceId;
         readonly model: 'Like';
      };
      readonly comment: {
         readonly namespace: 'public' & NamespaceId;
         readonly model: 'Comment';
      };
   };
   readonly domain: {
      readonly namespaces: {
         readonly public: {
            readonly models: {
               readonly Comment: {
                  readonly fields: {
                     readonly id: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                     readonly comment: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                     readonly created_at: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/timestamptz-temporal@1';
                        };
                     };
                     readonly userId: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                     readonly postId: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                  };
                  readonly relations: {
                     readonly post: {
                        readonly to: {
                           readonly namespace: 'public' & NamespaceId;
                           readonly model: 'Post';
                        };
                        readonly cardinality: 'N:1';
                        readonly nullable: false;
                        readonly on: {
                           readonly localFields: readonly ['postId'];
                           readonly targetFields: readonly ['id'];
                        };
                     };
                     readonly user: {
                        readonly to: {
                           readonly namespace: 'public' & NamespaceId;
                           readonly model: 'User';
                        };
                        readonly cardinality: 'N:1';
                        readonly nullable: false;
                        readonly on: {
                           readonly localFields: readonly ['userId'];
                           readonly targetFields: readonly ['id'];
                        };
                     };
                  };
                  readonly storage: {
                     readonly table: 'comment';
                     readonly namespaceId: 'public';
                     readonly fields: {
                        readonly id: { readonly column: 'id' };
                        readonly comment: { readonly column: 'comment' };
                        readonly created_at: { readonly column: 'created_at' };
                        readonly userId: { readonly column: 'userId' };
                        readonly postId: { readonly column: 'postId' };
                     };
                  };
               };
               readonly Follow: {
                  readonly fields: {
                     readonly followerId: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                     readonly followingId: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                     readonly createdAt: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/timestamptz-temporal@1';
                        };
                     };
                  };
                  readonly relations: {
                     readonly follower: {
                        readonly to: {
                           readonly namespace: 'public' & NamespaceId;
                           readonly model: 'User';
                        };
                        readonly cardinality: 'N:1';
                        readonly nullable: false;
                        readonly on: {
                           readonly localFields: readonly ['followerId'];
                           readonly targetFields: readonly ['id'];
                        };
                     };
                     readonly following: {
                        readonly to: {
                           readonly namespace: 'public' & NamespaceId;
                           readonly model: 'User';
                        };
                        readonly cardinality: 'N:1';
                        readonly nullable: false;
                        readonly on: {
                           readonly localFields: readonly ['followingId'];
                           readonly targetFields: readonly ['id'];
                        };
                     };
                  };
                  readonly storage: {
                     readonly table: 'follow';
                     readonly namespaceId: 'public';
                     readonly fields: {
                        readonly followerId: { readonly column: 'followerId' };
                        readonly followingId: {
                           readonly column: 'followingId';
                        };
                        readonly createdAt: { readonly column: 'createdAt' };
                     };
                  };
               };
               readonly Like: {
                  readonly fields: {
                     readonly userId: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                     readonly postId: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                  };
                  readonly relations: {
                     readonly post: {
                        readonly to: {
                           readonly namespace: 'public' & NamespaceId;
                           readonly model: 'Post';
                        };
                        readonly cardinality: 'N:1';
                        readonly nullable: false;
                        readonly on: {
                           readonly localFields: readonly ['postId'];
                           readonly targetFields: readonly ['id'];
                        };
                     };
                     readonly user: {
                        readonly to: {
                           readonly namespace: 'public' & NamespaceId;
                           readonly model: 'User';
                        };
                        readonly cardinality: 'N:1';
                        readonly nullable: false;
                        readonly on: {
                           readonly localFields: readonly ['userId'];
                           readonly targetFields: readonly ['id'];
                        };
                     };
                  };
                  readonly storage: {
                     readonly table: 'like';
                     readonly namespaceId: 'public';
                     readonly fields: {
                        readonly userId: { readonly column: 'userId' };
                        readonly postId: { readonly column: 'postId' };
                     };
                  };
               };
               readonly Post: {
                  readonly fields: {
                     readonly id: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                     readonly title: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                     readonly content: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                     readonly slug: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                     readonly created_at: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/timestamptz-temporal@1';
                        };
                     };
                     readonly published_at: {
                        readonly nullable: true;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/timestamptz-temporal@1';
                        };
                     };
                     readonly authorId: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                  };
                  readonly relations: {
                     readonly author: {
                        readonly to: {
                           readonly namespace: 'public' & NamespaceId;
                           readonly model: 'User';
                        };
                        readonly cardinality: 'N:1';
                        readonly nullable: false;
                        readonly on: {
                           readonly localFields: readonly ['authorId'];
                           readonly targetFields: readonly ['id'];
                        };
                     };
                     readonly comments: {
                        readonly to: {
                           readonly namespace: 'public' & NamespaceId;
                           readonly model: 'Comment';
                        };
                        readonly cardinality: '1:N';
                        readonly on: {
                           readonly localFields: readonly ['id'];
                           readonly targetFields: readonly ['postId'];
                        };
                     };
                     readonly likes: {
                        readonly to: {
                           readonly namespace: 'public' & NamespaceId;
                           readonly model: 'Like';
                        };
                        readonly cardinality: '1:N';
                        readonly on: {
                           readonly localFields: readonly ['id'];
                           readonly targetFields: readonly ['postId'];
                        };
                     };
                     readonly tags: {
                        readonly to: {
                           readonly namespace: 'public' & NamespaceId;
                           readonly model: 'Post_Tag';
                        };
                        readonly cardinality: '1:N';
                        readonly on: {
                           readonly localFields: readonly ['id'];
                           readonly targetFields: readonly ['postId'];
                        };
                     };
                  };
                  readonly storage: {
                     readonly table: 'post';
                     readonly namespaceId: 'public';
                     readonly fields: {
                        readonly id: { readonly column: 'id' };
                        readonly title: { readonly column: 'title' };
                        readonly content: { readonly column: 'content' };
                        readonly slug: { readonly column: 'slug' };
                        readonly created_at: { readonly column: 'created_at' };
                        readonly published_at: {
                           readonly column: 'published_at';
                        };
                        readonly authorId: { readonly column: 'authorId' };
                     };
                  };
               };
               readonly Post_Tag: {
                  readonly fields: {
                     readonly postId: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                     readonly tagId: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                  };
                  readonly relations: {
                     readonly post: {
                        readonly to: {
                           readonly namespace: 'public' & NamespaceId;
                           readonly model: 'Post';
                        };
                        readonly cardinality: 'N:1';
                        readonly nullable: false;
                        readonly on: {
                           readonly localFields: readonly ['postId'];
                           readonly targetFields: readonly ['id'];
                        };
                     };
                     readonly tag: {
                        readonly to: {
                           readonly namespace: 'public' & NamespaceId;
                           readonly model: 'Tag';
                        };
                        readonly cardinality: 'N:1';
                        readonly nullable: false;
                        readonly on: {
                           readonly localFields: readonly ['tagId'];
                           readonly targetFields: readonly ['id'];
                        };
                     };
                  };
                  readonly storage: {
                     readonly table: 'post_Tag';
                     readonly namespaceId: 'public';
                     readonly fields: {
                        readonly postId: { readonly column: 'postId' };
                        readonly tagId: { readonly column: 'tagId' };
                     };
                  };
               };
               readonly Tag: {
                  readonly fields: {
                     readonly id: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                     readonly name: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                  };
                  readonly relations: {
                     readonly postTags: {
                        readonly to: {
                           readonly namespace: 'public' & NamespaceId;
                           readonly model: 'Post_Tag';
                        };
                        readonly cardinality: '1:N';
                        readonly on: {
                           readonly localFields: readonly ['id'];
                           readonly targetFields: readonly ['tagId'];
                        };
                     };
                  };
                  readonly storage: {
                     readonly table: 'tag';
                     readonly namespaceId: 'public';
                     readonly fields: {
                        readonly id: { readonly column: 'id' };
                        readonly name: { readonly column: 'name' };
                     };
                  };
               };
               readonly User: {
                  readonly fields: {
                     readonly id: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                     readonly name: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                     readonly email: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                     readonly bio: {
                        readonly nullable: true;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                     readonly password: {
                        readonly nullable: false;
                        readonly type: {
                           readonly kind: 'scalar';
                           readonly codecId: 'pg/text@1';
                        };
                     };
                  };
                  readonly relations: {
                     readonly comments: {
                        readonly to: {
                           readonly namespace: 'public' & NamespaceId;
                           readonly model: 'Comment';
                        };
                        readonly cardinality: '1:N';
                        readonly on: {
                           readonly localFields: readonly ['id'];
                           readonly targetFields: readonly ['userId'];
                        };
                     };
                     readonly followers: {
                        readonly to: {
                           readonly namespace: 'public' & NamespaceId;
                           readonly model: 'Follow';
                        };
                        readonly cardinality: '1:N';
                        readonly on: {
                           readonly localFields: readonly ['id'];
                           readonly targetFields: readonly ['followerId'];
                        };
                     };
                     readonly following: {
                        readonly to: {
                           readonly namespace: 'public' & NamespaceId;
                           readonly model: 'Follow';
                        };
                        readonly cardinality: '1:N';
                        readonly on: {
                           readonly localFields: readonly ['id'];
                           readonly targetFields: readonly ['followingId'];
                        };
                     };
                     readonly likes: {
                        readonly to: {
                           readonly namespace: 'public' & NamespaceId;
                           readonly model: 'Like';
                        };
                        readonly cardinality: '1:N';
                        readonly on: {
                           readonly localFields: readonly ['id'];
                           readonly targetFields: readonly ['userId'];
                        };
                     };
                     readonly posts: {
                        readonly to: {
                           readonly namespace: 'public' & NamespaceId;
                           readonly model: 'Post';
                        };
                        readonly cardinality: '1:N';
                        readonly on: {
                           readonly localFields: readonly ['id'];
                           readonly targetFields: readonly ['authorId'];
                        };
                     };
                  };
                  readonly storage: {
                     readonly table: 'user';
                     readonly namespaceId: 'public';
                     readonly fields: {
                        readonly id: { readonly column: 'id' };
                        readonly name: { readonly column: 'name' };
                        readonly email: { readonly column: 'email' };
                        readonly bio: { readonly column: 'bio' };
                        readonly password: { readonly column: 'password' };
                     };
                  };
               };
            };
         };
      };
   };
   readonly capabilities: {
      readonly postgres: {
         readonly distinctOn: true;
         readonly jsonAgg: true;
         readonly lateral: true;
         readonly limit: true;
         readonly orderBy: true;
         readonly returning: true;
      };
      readonly sql: {
         readonly checkConstraint: true;
         readonly defaultInInsert: true;
         readonly enums: true;
         readonly lateral: true;
         readonly returning: true;
         readonly scalarList: true;
      };
   };
   readonly extensions: {};
   readonly execution: {
      readonly executionHash: ExecutionHash;
      readonly mutations: {
         readonly defaults: readonly [
            {
               readonly ref: {
                  readonly namespace: 'public';
                  readonly table: 'comment';
                  readonly column: 'id';
               };
               readonly onCreate: {
                  readonly kind: 'generator';
                  readonly id: 'uuidv4';
               };
            },
            {
               readonly ref: {
                  readonly namespace: 'public';
                  readonly table: 'post';
                  readonly column: 'id';
               };
               readonly onCreate: {
                  readonly kind: 'generator';
                  readonly id: 'uuidv4';
               };
            },
            {
               readonly ref: {
                  readonly namespace: 'public';
                  readonly table: 'tag';
                  readonly column: 'id';
               };
               readonly onCreate: {
                  readonly kind: 'generator';
                  readonly id: 'uuidv4';
               };
            },
            {
               readonly ref: {
                  readonly namespace: 'public';
                  readonly table: 'user';
                  readonly column: 'id';
               };
               readonly onCreate: {
                  readonly kind: 'generator';
                  readonly id: 'uuidv4';
               };
            },
         ];
      };
   };
   readonly meta: {};

   readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
